### ISSUE TITLE
F20-7pm-d Custom Search via Google

### ISSUE THREAD

**Issue by andrewhlu** [ucsb-cs156-s21/proj-mapache-search#7]
As a user, I'd like to be able to search for topics via a Google custom search in order to get help with course assignments.

(Note: this feature becomes more compelling when combined with a global search over the slack workspace!)

- [x] As a user I can perform a custom google search.  Initially, we'll use a global google search api token, aware of the fact that this is not a sustainable strategy, since such tokens are limited to 100 searches per day. 
- [x] As a user I can add a custom google search api token to my account, so that I can enable searching from within the mapache search app for up to 100 searches per user per day.
- [x] As a user when I try to do a google search, it always uses my personal google api token and never the global one; and if I don't have a token defined, it refuses to do a search.
- [x] As a user I can see how many searches I have left on my personal google api token before it expires, and when the next reset will take place.
- [x] As an admin I can see on the list of all users,(a) which users have entered a google api search token, and which have not, (b) how many searches each user has left on their token and (c) when each users token expires.
- [ ] ~~~As a member, each time I do a google search, an entry is made in a log table of google searches performed.    This table should probably be a Mongo table (because of the 10K row limit of the free tier of Heroku).    The log should include the user id, date time-stamp, and the search query.~~~ (NOW ISSUE #227 )
- [ ] ~~~As an admin, I can see a table of all users with the number of searches peformed.~~~  (NOW ISSUE #227 )
- [ ] ~~~As an admin, there is a link from each user in the user table to list of their searches~~~ (We'll add this later if there is a real need for it.)

Once the story above for entering a personal google search api token is implemented, the personal google search api token should always be used (and searches prohibited if that  using my personal google search api token.

**Comment by pconrad** [comment]
Closing: all stories have either been implemented, moved to other issues, or deemed not a priority.
